#!/usr/bin/env python3
"""Generate a lightweight metadata index for the US Code XML files."""

from __future__ import annotations

import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Dict

import xml.etree.ElementTree as ET

REPO_ROOT = Path(__file__).resolve().parents[1]
USC_DIR = REPO_ROOT / "usc"
OUTPUT_FILE = REPO_ROOT / "data" / "titles.json"
CHUNKED_TITLES = {
    # Titles too large to ship (or load in a browser) as a single XML file.
    # Each entry maps a title's XML stem to the manifest the website should
    # load instead. The chunk manifest and per-section files are generated by
    # tools/build_title42_chunks.py and are never committed to the repository;
    # they are produced fresh during the Pages build, immediately before the
    # original usc/usc42.xml is removed from the publishable source.
    "usc42": REPO_ROOT / "data" / "title-42" / "manifest.json",
}
NS = {
    "uslm": "http://xml.house.gov/schemas/uslm/1.0",
    "dc": "http://purl.org/dc/elements/1.1/",
}
ROOT_TAGS = {
    f"{{{NS['uslm']}}}title",
    f"{{{NS['uslm']}}}appendix",
    f"{{{NS['uslm']}}}division",
    f"{{{NS['uslm']}}}subtitle",
}


def _clean(text: str | None) -> str:
    if text is None:
        return ""
    return " ".join(text.split())


def _pointer_metadata(xml_path: Path) -> Dict[str, str]:
    name = xml_path.stem
    number = name[3:]
    label = f"Title {number}" if number else name
    return {
        "file": f"usc/{xml_path.name}",
        "identifier": "",
        "number": number,
        "heading": f"{label} (data stored via Git LFS; fetch required)",
        "pointer": True,
    }


def _chunked_metadata(stem: str, manifest_path: Path) -> Dict[str, str] | None:
    if not manifest_path.exists():
        return None
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    metadata = manifest.get("metadata", {})
    manifest_rel = manifest_path.relative_to(REPO_ROOT).as_posix()
    number = metadata.get("number") or stem[3:]
    heading = metadata.get("heading") or f"Title {number}"
    label = metadata.get("label") or f"Title {number}"
    return {
        # `file` stays the generic fetch key every other title also uses, so
        # the frontend does not need a separate code path just to find the
        # right URL; `manifest` is kept as an explicit alias for clarity/tools
        # that specifically expect a "manifest" field.
        "file": manifest_rel,
        "manifest": manifest_rel,
        "identifier": metadata.get("identifier", f"/us/usc/t{number}"),
        "number": number,
        "heading": heading,
        "label": label,
        "chunked": True,
    }


def extract_title_metadata(xml_path: Path) -> Dict[str, str]:
    chunk_manifest = CHUNKED_TITLES.get(xml_path.stem.lower())
    if chunk_manifest is not None:
        chunked = _chunked_metadata(xml_path.stem.lower(), chunk_manifest)
        if chunked is not None:
            return chunked
        # No manifest yet (e.g. chunks have not been built in this environment).
        # Fall through to the ordinary XML-based extraction below so local
        # development still works before the chunk-build step has run, as
        # long as the real usc42.xml is still present on disk.

    with xml_path.open("r", encoding="utf-8") as text_fh:
        first_line = text_fh.readline().strip()
        if first_line.startswith("version https://git-lfs.github.com"):
            return _pointer_metadata(xml_path)

    identifier = ""
    number = ""
    short_heading = ""
    long_heading = ""
    watching_root = False

    with xml_path.open("rb") as fh:
        context = ET.iterparse(fh, events=("start", "end"))
        for event, elem in context:
            tag = elem.tag
            if event == "start":
                if tag == f"{{{NS['uslm']}}}uscDoc" and not identifier:
                    identifier = elem.get("identifier", "")
                elif tag in ROOT_TAGS and not long_heading:
                    current_id = elem.get("identifier", "")
                    watching_root = True
                    if current_id.startswith("/us/usc/") and not identifier:
                        identifier = current_id
            elif event == "end":
                if tag == f"{{{NS['dc']}}}title" and not short_heading:
                    short_heading = _clean(elem.text)
                elif tag == f"{{{NS['uslm']}}}docNumber" and not number:
                    number = _clean(elem.text)
                elif watching_root and tag == f"{{{NS['uslm']}}}heading" and not long_heading:
                    long_heading = _clean(elem.text)
                elif watching_root and tag in ROOT_TAGS:
                    watching_root = False
                elem.clear()
            if short_heading and number and long_heading:
                break
        else:
            raise RuntimeError(f"Unable to extract metadata from {xml_path.name}")

    heading = long_heading if long_heading else short_heading
    return {
        "file": f"usc/{xml_path.name}",
        "identifier": identifier,
        "number": number,
        "heading": heading,
        "label": short_heading or heading,
    }


def build_index():
    entries = {}
    for xml_path in USC_DIR.glob("usc*.xml"):
        entries[xml_path.stem.lower()] = extract_title_metadata(xml_path)

    # A chunked title's source XML is deliberately removed from the
    # publishable tree after its chunks are built (see
    # tools/build_title42_chunks.py and the Pages workflow), so the glob
    # above will not find it in that environment. Make sure it is still
    # represented in the index using its manifest, sorted into the same
    # position its XML filename would have occupied (e.g. "usc42" between
    # "usc41" and "usc43").
    for stem, manifest_path in CHUNKED_TITLES.items():
        if stem in entries:
            continue
        chunked = _chunked_metadata(stem, manifest_path)
        if chunked is not None:
            entries[stem] = chunked

    titles = [entries[stem] for stem in sorted(entries)]
    return {
        "generated": datetime.now(UTC).isoformat(),
        "titles": titles,
    }


def main() -> int:
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    index = build_index()
    OUTPUT_FILE.write_text(json.dumps(index, indent=2))
    print(f"Wrote metadata for {len(index['titles'])} titles to {OUTPUT_FILE.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
